name: Push Workflow

on:
  push:
    branches:
      - main
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Code pushed to main branch"
